STEP 1 — LOAD PREPROCESSED DATASET

In [1]:
import pandas as pd
final_df = pd.read_csv(
    "preprocessed_resume_dataset.csv"
)

#### STEP 2 — CHECK DATASET

In [2]:
print(final_df.shape)
print(final_df.head())

(10035, 6)
                                         resume_text            category  \
0  EDUCATION\n© MBA - Executive Leadership © Bach...  Accountant resumes
1  HOWARD GERRARD\n\ncoo ie me\n\nees |= Verifyin...  Accountant resumes
2  SENIOR ACCOUNTANT\n= Qo ° in\ninfo@resumekrafi...  Accountant resumes
3  Olivia Ogilvy, Accountant\n1515 Pacific Ave, L...  Accountant resumes
4  Brooklyn, NY\nStephen Greet, CPA (128) 336-785...  Accountant resumes

     subfolder     file_name  length  \
0  Bing_images  Image_10.png     937
1  Bing_images  Image_11.jpg     357
2  Bing_images  Image_12.jpg    2814
3  Bing_images  Image_14.jpg     974
4  Bing_images  Image_16.jpg    1521

                                        cleaned_text
0  education mba executive leadership bachelor sc...
1  howard gerrard coo ie ee verifying financial d...
2  senior accountant qo info resumekraficom chica...
3  olivia ogilvy accountant pacific ave los angel...
4  brooklyn ny stephen greet cpa stephen beamjobs...

#### STEP 3 - Check columns

In [3]:
print(final_df.columns)

Index(['resume_text', 'category', 'subfolder', 'file_name', 'length',
       'cleaned_text'],
      dtype='object')

#### STEP 4 — CHECK CATEGORY COLUMN
##### This is the target column

In [4]:
print(
    final_df['category'].unique()
)

['Accountant resumes' 'Advocate resumes' 'Agricultural resumes'
 'Apparel resumes' 'Architects resumes' 'Arts resumes'
 'Automobile resumes' 'Aviation resumes' 'Banking resumes'
 'Blockchain resumes' 'BPO resumes' 'Building _Construction resumes'
 'Business Analyst resumes' 'Civil Engineer resumes' 'Consultant resumes'
 'data science resumes' 'Database resumes' 'Designing resumes'
 'DevOps Engineer resumes' 'Digital Media resumes'
 'DotNet Developer resumes' 'Education resumes'
 'Electrical Engineering resumes' 'ETL Developer resumes'
 'Finance resumes' 'Food_Beverages resumes' 'Health_Fitness resumes'
 'HR resumes' 'Information Technology resumes' 'Java Developer resumes'
 'Managment resumes' 'Mechanical Engineer resumes'
 'Network Security Engineer resumes' 'Operations Manager resumes'
 'PMO resumes' 'Public Relations resumes' 'Python Developer resumes'
 'React Developer resumes' 'Sales resumes' 'SAP Developer resumes'
 'SQL Developer resumes' 'Testing resumes' 'web designing resumes'
 'Accountant' 'Advocate' 'Agricultural' 'Arts' 'Aviation' 'Banking'
 'Consultant' 'Data Science' 'Database' 'Designer' 'DevOps Engineer'
 'Digital Media' 'Education' 'ETL Developer' 'Human Resources'
 'Information Technology' 'Management' 'Python Developer'
 'React Developer' 'SAP Developer' 'Testing' 'Agriculture' 'Apparel'
 'Architect' 'Automobile' 'Avian' 'Blockchain' 'Building'
 'BusinessAnalyst' 'CivilEngineer' 'Consult' 'DataScience' 'Design'
 'DevOpsEngineer' 'Digital' 'DOT' 'ElectricalEngineer' 'ETL' 'Finance'
 'Food' 'HealthFitness' 'HR' 'IT' 'JavaDeveloper' 'MechanicalEngineer'
 'NSE' 'OperationManager' 'PBO' 'PMO' 'Public' 'PythonDeveloper' 'React'
 'Sales' 'SAPDeveloper' 'SQL' 'WebDesigning']

#### STEP 5 — LABEL ENCODING
##### Deep learning models cannot understand text labels.Convert categories into numbers.

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
final_df['label'] = encoder.fit_transform(
    final_df['category']
)

#### STEP 6 — VERIFY LABELS

In [6]:
print(
    final_df[
        ['category', 'label']
    ].head(10)
)

             category  label
0  Accountant resumes      1
1  Accountant resumes      1
2  Accountant resumes      1
3  Accountant resumes      1
4  Accountant resumes      1
5  Accountant resumes      1
6  Accountant resumes      1
7  Accountant resumes      1
8  Accountant resumes      1
9  Accountant resumes      1

#### STEP 7 — CHECK NUMBER OF CLASSES

In [7]:
num_classes = final_df[
    'label'
].nunique()

print(f"{num_classes} resume categories")

99 resume categories

#### STEP 8 — DEFINE FEATURES & TARGET

##### X = Input Text
##### y = Labels

In [8]:
X = final_df['cleaned_text']
y = final_df['label']

#### STEP 9 — TRAIN TEST SPLIT

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#### STEP 10 — VERIFY SPLIT

In [10]:
print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

(8028,)
(2007,)
(8028,)
(2007,)

#### STEP 11 — Install transformers

In [11]:
pip install transformers datasets torch

Requirement already satisfied: transformers in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (5.6.2)
Requirement already satisfied: datasets in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (4.8.5)
Requirement already satisfied: torch in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (2.12.0+cpu)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (1.12.0)
Requirement already satisfied: numpy>=1.17 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: xxhash in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: setuptools<82 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\vanda\pycharmprojects\assignment_1\env\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\vanda\PycharmProjects\Assignment_1\env\scripts\python.exe -m pip install --upgrade pip

#### STEP 12 — Import BERT libraries

In [12]:
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments
)

import torch

#### STEP 13 — Load tokenizer

In [13]:
tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

#### STEP 14 — Tokenize resumes

In [14]:
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=256
)

test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=256
)

#### STEP 15 — Create PyTorch dataset class

In [15]:
class ResumeDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):

        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels.iloc[idx]
        )

        return item

    def __len__(self):

        return len(self.labels)

#### STEP 16 — Create train/test datasets

In [16]:
train_dataset = ResumeDataset(
    train_encodings,
    y_train
)

test_dataset = ResumeDataset(
    test_encodings,
    y_test
)

#### STEP 17 — Load DistilBERT model

In [17]:
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_classes
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

#### STEP 18 — Training configuration

In [18]:
pip install accelerate>=1.1.0

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: C:\Users\vanda\PycharmProjects\Assignment_1\env\scripts\python.exe -m pip install --upgrade pip

In [19]:
training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=4,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    eval_strategy="epoch",

    save_strategy="epoch",

    load_best_model_at_end=True
)

#### STEP 19 — Create trainer

In [20]:
trainer = Trainer(
    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=test_dataset
)

#### STEP 20 — Train model

In [21]:
trainer.train()

C:\Users\vanda\PycharmProjects\Assignment_1\env\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\vanda\PycharmProjects\Assignment_1\env\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\vanda\PycharmProjects\Assignment_1\env\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\vanda\PycharmProjects\Assignment_1\env\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4016, training_loss=1.2741161796201272, metrics={'train_runtime': 43370.827, 'train_samples_per_second': 0.74, 'train_steps_per_second': 0.093, 'total_flos': 2130575780339712.0, 'train_loss': 1.2741161796201272, 'epoch': 4.0})

#### STEP 21 — Evaluate model

In [22]:
results = trainer.evaluate()

print(results)

C:\Users\vanda\PycharmProjects\Assignment_1\env\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.9826273322105408}

#### STEP 22 — Predict a resume

In [24]:
text = "Python developer with Django and AWS experience"

inputs = tokenizer(
    text,
    return_tensors="pt",
    truncation=True,
    padding=True
)

outputs = model(**inputs)

predicted_class = outputs.logits.argmax().item()

print(
    encoder.inverse_transform([predicted_class])
)

['PythonDeveloper']

#### STEP 23 — Save model

In [25]:
model.save_pretrained("./resume_classifier")

tokenizer.save_pretrained("./resume_classifier")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./resume_classifier\\tokenizer_config.json',
 './resume_classifier\\tokenizer.json')

In [27]:
import os

print(os.listdir("resume_classifier"))

['config.json', 'model.safetensors', 'tokenizer.json', 'tokenizer_config.json']

In [28]:
import joblib

joblib.dump(encoder, "label_encoder.pkl")

['label_encoder.pkl']

In [29]:
import joblib

loaded_encoder = joblib.load("label_encoder.pkl")
print(len(loaded_encoder.classes_))

99

In [33]:
import joblib

joblib.dump(
    encoder,
    "label_encoder.pkl"
)

print("Encoder Saved")

Encoder Saved

In [34]:
import joblib

encoder = joblib.load("label_encoder.pkl")

print(len(encoder.classes_))

99